### ISSUE TITLE
🛠️ Fix: docker compose env파일 경로 추가

### ISSUE THREAD

**Issue by RinRinPARK** [swm-standard/Phote_BE#169]
### 🐞 상세 설명

- 그냥 유저이름 박으면 되는데.. 굳이굳이 env파일을 사용하고 싶습니다....... 흐헤헤 나중에 쓸 일이 있을지도 모르니까..

---

### 📌 To-Do

- [ ] todo

---

### 🙌🏻 기타 참고 사항

기타 사항

---

**Comment by camrionnvmff** [comment]
env 파일을 사용하여 프로젝트의 환경 변수를 관리합니다.docker-compose.yml 파일에서 env 파일을 사용하는 방법은 다음과 같습니다.

먼저 프로젝트 루트 디렉토리에.env 파일을 생성합니다.예:

DB_USER=myuser
DB_PASSWORD=mypassword
그런 다음 docker-compose.yml 파일에 env_file 옵션을 추가합니다.

version: '3.8'

services:
db:
image: postgres:latest
env_file:
- .env
ports:
- "5432:5432"
volumes:
- db-data:/var/lib/postgresql/data

volumes:
db-data:
이렇게 하면 Docker Compose는.env 파일에 정의된 환경 변수를 자동으로 로드합니다.
로컬 환경 관리의 경우 MAC을 사용하는 경우 Servbay를 사용하여 시도할 수 있습니다.
