### ISSUE TITLE
✨ Feat: Swagger 연동

### ISSUE THREAD

**Issue by adorableco** [swm-standard/Phote_BE#78]
### ✨ 기능 설명

설명 작성

---

### 📌 To-Do

- [ ] todo

---

### 🙌🏻 기타 참고 사항

기타 사항

---

**Comment by Goonco** [comment]
이거 pr에 저도 리뷰어 넣어주세요\~\~

**Comment by adorableco** [comment]
> 이거 pr에 저도 리뷰어 넣어주세요\~\~

예엡~!!
